### ISSUE TITLE
e2e testing

### ISSUE THREAD

**Issue by beshad** [DavideViolante/Angular-Full-Stack#191]
hi guys, 

New user of this awesome angular full stack and just finished scaffolding a new project. other tests work fine but i am getting an error with `ng e2e` test (`npm start` running): 

```
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.76 MB [initial] [rendered]
ℹ ｢wdm｣: Compiled successfully.
[13:57:04] I/update - chromedriver: file exists /code/MY_PROJECT/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.40.zip
[13:57:04] I/update - chromedriver: unzipping chromedriver_2.40.zip
[13:57:04] I/update - chromedriver: setting permissions to 0755 for /code/MY_PROJECT/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.40
[13:57:04] I/update - chromedriver: chromedriver_2.40 up to date
/code/MY_PROJECT/node_modules/protractor/built/runner.js:1
(function (exports, require, module, __filename, __dirname) { �
                                                               ^
```

```
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/code/MY_PROJECT/node_modules/protractor/built/launcher.js:12:18)
An unexpected error occured: undefined
```

i have not changed the backend/api (Node 8.11) so not sure where the error is coming from. any suggestions? many thanks

**Comment by DavideViolante** [comment]
npm start is not needed for ng e2e, but I don't think this solves your error.

**Comment by beshad** [comment]
problem was solved by removing node_modules folder and running npm install again. i guess protractor wasn't installed properly. cheers
