### ISSUE TITLE
Error running dev & prod scripts

### ISSUE THREAD

**Issue by trydalch** [DavideViolante/Angular-Full-Stack#208]
I've tried running each of the commands for these two scripts separately (without concurrently), but when I run `npm run-script dev` or `npm run-script prod`, I get the following output:

### dev
`
> angular2-full-stack@7.2.1 predev C:\Users\Trevor.Rydalch\source\repos\Angular-Full-Stack
> tsc -p server

> angular2-full-stack@7.2.1 dev C:\Users\Trevor.Rydalch\source\repos\Angular-Full-Stack
> concurrently "ng serve --proxy-config proxy.conf.json --open" "tsc -w -p server" "nodemon dist/server/app.js"

[0] Error occurred when executing command: ng serve --proxy-config proxy.conf.json --open
[0] Error: spawn cmd.exe ENOENT
[0]     at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
[0]     at onErrorNT (internal/child_process.js:407:16)
[0]     at process._tickCallback (internal/process/next_tick.js:63:19)
[0]     at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
[0]     at startup (internal/bootstrap/node.js:282:19)
[0]     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
[1] Error occurred when executing command: tsc -w -p server
[1] Error: spawn cmd.exe ENOENT
[1]     at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
[1]     at onErrorNT (internal/child_process.js:407:16)
[1]     at process._tickCallback (internal/process/next_tick.js:63:19)
[1]     at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
[1]     at startup (internal/bootstrap/node.js:282:19)
[1]     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
[2] Error occurred when executing command: nodemon dist/server/app.js
[2] Error: spawn cmd.exe ENOENT
[2]     at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
[2]     at onErrorNT (internal/child_process.js:407:16)
[2]     at process._tickCallback (internal/process/next_tick.js:63:19)
[2]     at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
[2]     at startup (internal/bootstrap/node.js:282:19)
[2]     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
[2] nodemon dist/server/app.js exited with code -4058
[1] tsc -w -p server exited with code -4058
[0] ng serve --proxy-config proxy.conf.json --open exited with code -4058
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular2-full-stack@7.2.1 dev: `concurrently "ng serve --proxy-config proxy.conf.json --open" "tsc -w -p server" "nodemon dist/server/app.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-full-stack@7.2.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Trevor.Rydalch\AppData\Roaming\npm-cache\_logs\2019-02-24T02_32_35_003Z-debug.log`

### prod
`concurrently "ng build --aot --prod && tsc -p server && node dist/server/app.js"

[0] Error occurred when executing command: ng build --aot --prod && tsc -p server && node dist/server/app.js
[0] Error: spawn cmd.exe ENOENT
[0]     at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
[0]     at onErrorNT (internal/child_process.js:407:16)
[0]     at process._tickCallback (internal/process/next_tick.js:63:19)
[0]     at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
[0]     at startup (internal/bootstrap/node.js:282:19)
[0]     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
[0] ng build --aot --prod && tsc -p server && node dist/server/app.js exited with code -4058
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular2-full-stack@7.2.1 prod: `concurrently "ng build --aot --prod && tsc -p server && node dist/server/app.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-full-stack@7.2.1 prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Trevor.Rydalch\AppData\Roaming\npm-cache\_logs\2019-02-24T02_31_33_196Z-debug.log`

-----
Not sure what's causing the issue, but it seems related to concurrently.

**Comment by DavideViolante** [comment]
This this https://github.com/AtomLinter/linter-tidy/issues/68#issuecomment-234630051
or keep searching https://www.google.com/search?q=Error%3A+spawn+cmd.exe+ENOENT
This is not related to the project afaik.
