### ISSUE TITLE
After install error

### ISSUE THREAD

**Issue by infrarosso78** [DavideViolante/Angular-Full-Stack#213]
Hi, first of all congratulation on the project. Great piece of work!
I've tried to install and run the process but i get an error on first launch.

`MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
[3]     at new MongooseError (/Users/giovanni/dev/olinto/node_modules/mongoose/lib/error/mongooseError.js:10:11)
[3]     at NativeConnection.Connection.openUri (/Users/giovanni/dev/olinto/node_modules/mongoose/lib/connection.js:520:11)
[3]     at Mongoose.connect (/Users/giovanni/dev/olinto/node_modules/mongoose/lib/index.js:328:15)
[3]     at Object.<anonymous> (/Users/giovanni/dev/olinto/dist/server/app.js:25:10)
[3]     at Module._compile (module.js:653:30)
[3]     at Object.Module._extensions..js (module.js:664:10)
[3]     at Module.load (module.js:566:32)
[3]     at tryModuleLoad (module.js:506:12)
[3]     at Function.Module._load (module.js:498:3)
[3]     at Function.Module.runMain (module.js:694:10)
[3]     at startup (bootstrap_node.js:204:16)
[3]     at bootstrap_node.js:625:3
[3] [nodemon] app crashed - waiting for file changes before starting...`

I am using a local mongoDB installed via homebrew on mac (it's the community edition 4.2) and cannot really manage to make it work. Any idea?
Thanks in advance!

**Comment by DavideViolante** [comment]
It seems like it's failing at this line https://github.com/DavideViolante/Angular-Full-Stack/blob/master/server/app.ts#L26
Are you sure you have the .env file with the correct mongodb configuration? It seems like `mongodbURI` variable is undefined to you. Try to print it before line 26 to check its value.

**Comment by infrarosso78** [comment]
it is indeed undefined. And I've no .env file... how is that possible?
