### ISSUE TITLE
error on npm start

### ISSUE THREAD

**Issue by isaklafleur** [DavideViolante/Angular-Full-Stack#29]
Hi Davide,

I get this error when I run npm start

Do you know how to fix?

```
  angular2-full-stack git:(master) ✗ npm start

> angular2-full-stack@3.4.0-rc.1 start /Users/isaklafleur/Coding/GitHub/angular2-full-stack
> concurrently "mongod" "ng build -w" "nodemon src/server/app.js"

[0] 2017-03-08T13:54:19.298+0100 I CONTROL  [initandlisten] MongoDB starting : pid=4696 port=27017 dbpath=/data/db 64-bit host=Isaks-MBP.lan
[0] 2017-03-08T13:54:19.299+0100 I CONTROL  [initandlisten] db version v3.4.2
[0] 2017-03-08T13:54:19.299+0100 I CONTROL  [initandlisten] git version: 3f76e40c105fc223b3e5aac3e20dcd026b83b38b
[0] 2017-03-08T13:54:19.299+0100 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017
[0] 2017-03-08T13:54:19.299+0100 I CONTROL  [initandlisten] allocator: system
[0] 2017-03-08T13:54:19.299+0100 I CONTROL  [initandlisten] modules: none
[0] 2017-03-08T13:54:19.299+0100 I CONTROL  [initandlisten] build environment:
[0] 2017-03-08T13:54:19.299+0100 I CONTROL  [initandlisten]     distarch: x86_64
[0] 2017-03-08T13:54:19.299+0100 I CONTROL  [initandlisten]     target_arch: x86_64
[0] 2017-03-08T13:54:19.299+0100 I CONTROL  [initandlisten] options: {}
[0] 2017-03-08T13:54:19.303+0100 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
[0] 2017-03-08T13:54:19.303+0100 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=3584M,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
[0] 2017-03-08T13:54:20.201+0100 I CONTROL  [initandlisten]
[0] 2017-03-08T13:54:20.202+0100 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
[0] 2017-03-08T13:54:20.202+0100 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
[0] 2017-03-08T13:54:20.202+0100 I CONTROL  [initandlisten]
[0] 2017-03-08T13:54:20.243+0100 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
[0] 2017-03-08T13:54:20.244+0100 I NETWORK  [thread1] waiting for connections on port 27017
[2] [nodemon] 1.11.0
[2] [nodemon] to restart at any time, enter `rs`
[2] [nodemon] watching: *.*
[2] [nodemon] starting `node src/server/app.js`
[0] 2017-03-08T13:54:21.190+0100 I NETWORK  [thread1] connection accepted from 127.0.0.1:51585 #1 (1 connection now open)
[0] 2017-03-08T13:54:21.202+0100 I NETWORK  [conn1] received client metadata from 127.0.0.1:51585 conn1: { driver: { name: "nodejs", version: "2.2.24" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "16.4.0" }, platform: "Node.js v6.10.0, LE, mongodb-core: 2.1.8" }
[2] Connected to MongoDB
[2] Angular 2 Full Stack listening on port 3000
[1] Cannot read property 'config' of null
[1] TypeError: Cannot read property 'config' of null
[1]     at Class.run (/Users/isaklafleur/Coding/GitHub/angular2-full-stack/node_modules/@angular/cli/tasks/build.js:16:56)
[1]     at Class.run (/Users/isaklafleur/Coding/GitHub/angular2-full-stack/node_modules/@angular/cli/commands/build.js:143:26)
[1]     at Class.<anonymous> (/Users/isaklafleur/Coding/GitHub/angular2-full-stack/node_modules/@angular/cli/ember-cli/lib/models/command.js:134:17)
[1]     at process._tickCallback (internal/process/next_tick.js:103:7)
[1] ng build -w exited with code 1
[2] GET / 404 8.932 ms - 161
[2] Error: ENOENT: no such file or directory, stat '/Users/isaklafleur/Coding/GitHub/angular2-full-stack/dist/index.html'
[2]     at Error (native)
```

**Comment by DavideViolante** [comment]
I don't know exactly, but it should be something regarding the latest updates of Angular-CLI and the `.angular-cli.json` file (the config). My suggestions are:
- update your local angular-cli `npm i -g @angular/cli`
- delete node_modules of my project and re-run `npm i`

**Comment by DavideViolante** [comment]
Any news?
