### ISSUE TITLE
Cannot read property config of null

### ISSUE THREAD

**Issue by WebTalentTop** [DavideViolante/Angular-Full-Stack#44]
There was no problem when I ran this app first time.
I haved added features and customized it as its purpose.
It worked fine in my repo.
I have commited to my git repo and cloned it in other com or folder.
But I get this error.
Cannot read property 'config' of null
[1] TypeError: Cannot read property 'config' of null
[1]     at Class.run (/Volumes/Works/PokerNoteApp/node_modules/@angular/cli/tasks/serve.js:22:63)
[1]     at check_port_1.checkPort.then.port (/Volumes/Works/PokerNoteApp/node_modules/@angular/cli/commands/serve.js:103:26)
[1]     at process._tickCallback (internal/process/next_tick.js:103:7)

Please help me!

**Comment by WebTalentTop** [comment]
Maybe this is related to AngularCLI.
But I have no idea about it.

**Comment by DavideViolante** [comment]
Do you have a file called `.angular-cli.json`? This should be the config file...
Try reinstalling the cli by the way

**Comment by WebTalentTop** [comment]
Thank you, .angular-cli.json was hidden file so it caused this problem.
This is great boilerplate I have ever see.
Best regards!
