### ISSUE TITLE
Error : npm run prod

### ISSUE THREAD

**Issue by upex** [DavideViolante/Angular-Full-Stack#67]
Node v6.9.2
NPM 3.10.9
I am getting the below errors while try to run npm run prod  :

ENOENT: no such file or directory, open '/usr/local/data/workspace/app/Angular-Full-Stack/schema/loader.json'
Error: ENOENT: no such file or directory, open '/usr/local/data/workspace/app/Angular-Full-Stack/schema/loader.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at validateOptions (/usr/local/data/workspace/app/Angular-Full-Stack/node_modules/schema-utils/dist/validateOptions.js:35:27)
    at Function.ExtractTextPlugin.extract (/usr/local/data/workspace/app/Angular-Full-Stack/node_modules/extract-text-webpack-plugin/index.js:206:3)
    at rules.push.baseRules.map (/usr/local/data/workspace/app/Angular-Full-Stack/node_modules/@angular/cli/models/webpack-configs/styles.js:172:66)
    at Array.map (native)
    at Object.getStylesConfig (/usr/local/data/workspace/app/Angular-Full-Stack/node_modules/@angular/cli/models/webpack-configs/styles.js:160:33)
    at NgCliWebpackConfig.buildConfig (/usr/local/data/workspace/app/Angular-Full-Stack/node_modules/@angular/cli/models/webpack-config.js:21:31)
    at Class.run (/usr/local/data/workspace/app/Angular-Full-Stack/node_modules/@angular/cli/tasks/build.js:27:92)
    at Class.run (/usr/local/data/workspace/app/Angular-Full-Stack/node_modules/@angular/cli/commands/build.js:149:26)
    at Class.Command.validateAndRun (/usr/local/data/workspace/app/Angular-Full-Stack/node_modules/@angular/cli/ember-cli/lib/models/command.js:128:15)
    at /usr/local/data/workspace/app/Angular-Full-Stack/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:92:22
    at tryCatch (/usr/local/data/workspace/app/Angular-Full-Stack/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/usr/local/data/workspace/app/Angular-Full-Stack/node_modules/rsvp/dist/rsvp.js:554:13)
    at /usr/local/data/workspace/app/Angular-Full-Stack/node_modules/rsvp/dist/rsvp.js:629:16

**Comment by DavideViolante** [comment]
This project hasn't any loader.json file. Have you made some changes to my project?

**Comment by upex** [comment]
Not exactly.Got the issue resolved as there was a mismatch in global and local angular-cli version.
