### ISSUE TITLE
How to deploy on AWS EC2 instance

### ISSUE THREAD

**Issue by upex** [DavideViolante/Angular-Full-Stack#98]
node : v6.10.0
npm : 3.10.10
Hi DavideViolante, i tried to deploy the project in an aws ec2 instance and while running npm run prod encountered the below exit code 137. Any suggestion how to deploy it correctly ?
...
11% building modules 14/14 modules 0 active
[0] /bin/sh: line 1: 14219 Killed                  ng build -aot -prod
[0] ng build -aot -prod && tsc -p server && node dist/server/app.js exited with code 137

**Comment by DavideViolante** [comment]
I'm not very expert with EC2 but I think you should create the production bundle before uploading the code in the cloud. I would run npm run prod locally, then upload the code on the server (including the bundle in dist), then let it run with npm start.

**Comment by upex** [comment]
I guess it would work great that way for a single contributor project but will definitely be a problem for multiple contributor one to do the same. Thanks for your suggestion.

**Comment by Mean563** [comment]
@upex , I was trying deploy the my application on EC2 Instance, but I guess Almost done, but I am not able to connect the Mongo DB.

**Normally we have like below 👍 for Devlopment Env:**
`MONGODB_URI = mongodb://localhost:27017/test`
**I was changed prod Env like below :** 
`MONGODB_URI = mongodb://root:jPrhaDf83SrZ@ec2-18-220-198-78.us-east-2.compute.amazonaws.com/3000/test`

but I am getting below Error:
```
connection error: { MongoError: failed to connect to server [ec2-18-220-198-78.us-east-2.compute.amazonaws.com:27017] on first connect [MongoError: connect ECONNREFUSED 172.31.22.170:27017]
    at Pool.<anonymous> (/opt/bitnami/apps/git3/node_modules/mongodb-core/lib/topologies/server.js:329:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/opt/bitnami/apps/git3/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Connection.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/opt/bitnami/apps/git3/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Socket.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'MongoError',
  message: 'failed to connect to server [ec2-18-220-198-78.us-east-2.compute.amazonaws.com:27017] on first connect [MongoError: connect ECONNREFUSED 172.31.22.170:27017]' }

```
could you please help me what we can do for fix this.
Thanks in advance !!!

**Comment by upex** [comment]
@Mean563, make sure the below things are in place : 
 * mongod instance is running and working on the ec2 instance
* In your Security Group add Custom TCP Rule for 27017 port.
   Inbound > Edit > Add Rule > Custom TCP Rule, Port Range: 27017, custom source 0.0.0.0/0
* In /etc/mongod.conf: 
     Uncomment port=27017 
     Comment out bind_ip=127.0.0.1
Let me know if it works out!

**Comment by Mean563** [comment]
@upex, thank you so much for your response,  I am not able to see the mongod.conf file in etc folder, is some where i did wrong? 

How can we check whether mongod is running or not on ec2 instance. 
I was tried using below command to check 

```
bitnami@ip-172-31-22-170:/etc$ sudo mongod
2017-08-12T14:50:47.669+0000 I CONTROL  [initandlisten] MongoDB starting : pid=10094 port=27017 dbpath=/data/db 64-bit host=ip-172-31-22-170
2017-08-12T14:50:47.669+0000 I CONTROL  [initandlisten] db version v3.4.5
2017-08-12T14:50:47.669+0000 I CONTROL  [initandlisten] git version: 520b8f3092c48d934f0cd78ab5f40fe594f96863
2017-08-12T14:50:47.669+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2017-08-12T14:50:47.669+0000 I CONTROL  [initandlisten] modules: none
2017-08-12T14:50:47.669+0000 I CONTROL  [initandlisten] build environment:
2017-08-12T14:50:47.669+0000 I CONTROL  [initandlisten]     distarch: x86_64
2017-08-12T14:50:47.669+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2017-08-12T14:50:47.669+0000 I CONTROL  [initandlisten] options: {}
2017-08-12T14:50:47.669+0000 I STORAGE  [initandlisten] exception in initAndListen: 29 Data directory /data/db not found., terminating
2017-08-12T14:50:47.669+0000 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
2017-08-12T14:50:47.669+0000 I NETWORK  [initandlisten] shutdown: going to flush diaglog...
2017-08-12T14:50:47.669+0000 I CONTROL  [initandlisten] now exiting
2017-08-12T14:50:47.669+0000 I CONTROL  [initandlisten] shutting down with code:100
```
 
could you please suggest me. Thanks in advance !

**Comment by upex** [comment]
Hey @Mean563 , then mongod.conf file might be in /usr/local/etc/ location.
If nothing works you can find it out by mongo cmd : 
In the terminal 
-> mongo
> use admin
> db.runCommand( { getCmdLineOpts: 1 } ) 
##possible output
{
	"argv" : [
		"/usr/local/opt/mongodb/bin/mongod",
		"--config",
		"/usr/local/etc/mongod.conf"
	],
	"parsed" : {
		"config" : "/usr/local/etc/mongod.conf",
		"net" : {
			"bindIp" : "127.0.0.1"
		},
		"storage" : {
			"dbPath" : "/usr/local/var/mongodb"
		},
		"systemLog" : {
			"destination" : "file",
			"logAppend" : true,
			"path" : "/usr/local/var/log/mongodb/mongo.log"
		}
	},
	"ok" : 1
}

There you go .Hope it will help!
